spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  data:
    mongodb:
      uri: ${MONGODB_URL}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  output:
    ansi:
      enabled: always

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${LOCAL_CLIENT_ID}
            client-secret: ${LOCAL_CLIENT_SECRET}
            scope: read:user,user:email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  enable-kotlin: false

langchain4j:
  google-ai-gemini:
    recommend:
      api-key: ${GEMINI_API_KEY}
      model-name: ${GEMINI_MODEL}
    report:
      api-key: ${GEMINI_REPORT_API_KEY}
      model-name: ${GEMINI_REPORT_MODEL}

openai:
  api-key: ${OPENAI_API_KEY}
  embedding-model: ${OPENAI_MODEL}

qdrant:
  host: ${QDRANT_URL}
  port: 6334
  api-key: ${QDRANT_API_KEY}
  collection-name: amateurs

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 1209600000

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret_key: ${AWS_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
    cloudfront:
      domain: ${CLOUD_FRONT_DOMAIN_NAME}

oauth:
  success-redirect-url: http://localhost:5173

cookie:
  domain: localhost
  secure: false

swagger:
  server:
    url: ${SERVER_URL}

verification:
  service:
    url: ${VERIFICATION_SERVICE_URL}

otel:
  service:
    name: amateurs-api-server
  traces:
    exporter: console
  metrics:
    exporter: none
  logs:
    exporter: none